[Unit]
After=network-online.target systemd-modules-load.service
Wants=network-online.target
ConditionPathExists=/sys/module/xt_RTPENGINE

[Service]
Restart=always
RestartSec=3
LimitNOFILE=65535
LimitNPROC=65535
LimitCORE=infinity
